Cleanup
openmicroscopy/webtest pull request #20
Opened 2016-11-24 15:14 UTC by jburel

Add more python code check
and exclude directories generating when prep for pypi upload
Check that travis is green and that gallery is still working

2016-11-28 14:55 UTC, atarkowska requested changes
You have to update `urls.py` accordingly otherwise views throws an exception like

```
TypeError: dataset() takes at least 2 arguments (2 given)
```

2016-12-01 09:55 UTC, jburel commented
@aleksandra-tarkowska did you have a chance to look at the changes?

2016-12-01 10:23 UTC, aleksandra-tarkowska commented
Going through that amount of changes line by line and checking each character is not possible. We need tests for that. How do you think we could go through.

As you are cleaning up the code, would you be ok to review `request.REQUEST`?

2016-12-01 10:28 UTC, jburel commented
The "characters" changes are done by travis.
Using the app will check if the urls changes are correctly made.

2016-12-01 10:48 UTC, atarkowska reviewed
I went briefly through all the changes in urls.py. Noticed one issue

2016-12-01 10:48 UTC, aleksandra-tarkowska commented on omero_webtest/urls.py
> -    url(r'^dataset_split_view/(?P<datasetId>[0-9]+)/',
still failing `TypeError: dataset_split_view() takes at least 2 arguments (2 given)`

2016-12-01 13:02 UTC, jburel commented on omero_webtest/urls.py
> -    url(r'^dataset_split_view/(?P<datasetId>[0-9]+)/',
are you sure you are running the latest change
This was fixed by 4eba3c2

2016-12-01 16:06 UTC, atarkowska commented on omero_webtest/urls.py
> -    url(r'^dataset_split_view/(?P<datasetId>[0-9]+)/',
I am afraid the same behaviour http://web-dev-merge.openmicroscopy.org/webtest/dataset_split_view/7/ I can reproduce locally in isolation.

2016-12-01 16:16 UTC, jburel commented on omero_webtest/urls.py
> -    url(r'^dataset_split_view/(?P<datasetId>[0-9]+)/',
found the culprit ``dataset_split_include``

2016-12-01 16:32 UTC, atarkowska approved these changes

2016-12-02 12:08 UTC, jburel commented
Tested today the "split_view_figure": no crash when clicking on save. Just the csrf message.
@aleksandra-tarkowska and I discussed the csrf issue. this will be reviewed in another PR

2016-12-02 12:21 UTC, aleksandra-tarkowska commented
As discussed with @jburel request.REQUEST will be reviewed in another PR as well. My proposal is to write few simple tests like https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroWeb/test/integration/test_csrf.py that will allow to review both in one go

2016-12-02 12:21 UTC, merged